"""
    academic-observatory-workflows API

    The REST API for accessing data from academic-observatory-workflows.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: agent@observatory.academy
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import package.client
from package.client.model.query_response import QueryResponse


class TestQueryResponse(unittest.TestCase):
    """QueryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryResponse(self):
        """Test QueryResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = QueryResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
