# flake8: noqa

"""
    academic-observatory-workflows API

    The REST API for accessing data from academic-observatory-workflows.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: agent@observatory.academy
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from package.client.api_client import ApiClient

# import Configuration
from package.client.configuration import Configuration

# import exceptions
from package.client.exceptions import OpenApiException
from package.client.exceptions import ApiAttributeError
from package.client.exceptions import ApiTypeError
from package.client.exceptions import ApiValueError
from package.client.exceptions import ApiKeyError
from package.client.exceptions import ApiException
